kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wiremock-pv-claim
  namespace: REPLACE_NAMESPACE
  labels:
    app: wiremock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
