// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConnectivityCheckAPIRequest connectivity check api request
//
// swagger:model connectivity_check_api_request
type ConnectivityCheckAPIRequest struct {

	// API virtual IP or hostname.
	// Required: true
	Host *string `json:"host"`

	// API port
	// Required: true
	Port *int64 `json:"port"`

	// API scheme (http/https).
	// Required: true
	Scheme *string `json:"scheme"`
}

// Validate validates this connectivity check api request
func (m *ConnectivityCheckAPIRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHost(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheme(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConnectivityCheckAPIRequest) validateHost(formats strfmt.Registry) error {

	if err := validate.Required("host", "body", m.Host); err != nil {
		return err
	}

	return nil
}

func (m *ConnectivityCheckAPIRequest) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

func (m *ConnectivityCheckAPIRequest) validateScheme(formats strfmt.Registry) error {

	if err := validate.Required("scheme", "body", m.Scheme); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConnectivityCheckAPIRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectivityCheckAPIRequest) UnmarshalBinary(b []byte) error {
	var res ConnectivityCheckAPIRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
